binX_(n, p, x)
bin_x(n, p, x)
bindens(n, p, x)
bindist(n, p, x)
chi2X_(n, x)
chi2_x(n, x)
chi2dens(n, x)
chi2dist(n, x)
combi(n, x)
fX_(n1, n2, x)
f_x(n1, n2, x)
fdist(n1, n2, f)
gamma(x)
loggamma(x)
newton_a(y, ini, epsilon = 1.0e-6, limit = 30)
normal__X_(z)
normal___x(z)
normaldist(z)
normalxXX_(z)
normalx__x(z)
p_nor(z)
p_t(df, t)
pchi2(n, y)
pchi2X_(n, y)
pchi2_x(n, y)
pchi2dist(n, y)
perm(n, x = n)
pf(q, n1, n2)
pfX_(n1, n2, x)
pf_x(n1, n2, x)
pfdist(n1, n2, y)
pfsub(x, y, z)
pnorm(qn)
pnormal__X_(y)
pnormal___x(y)
pnormaldist(y)
pnormalxXX_(z)
pnormalx__x(y)
poissonX_(m, x)
poisson_x(m, x)
poissondens(m, x)
poissondist(m, x)
pt(q, n)
pt__X_(n, y)
pt___x(n, y)
ptdist(n, y)
ptsub(q, n)
ptxXX_(n, y)
ptx__x(n, y)
q_chi2(df, chi2)
q_f(df1, df2, f)
t__X_(n, x)
t___x(n, x)
tdist(n, t)
txXX_(n, x)
tx__x(n, x)
